### ISSUE TITLE
Additional notation 

### ISSUE THREAD

**Issue by sensibol** [lenmus/lomse#117]
I want some additional notations to be displayed. Below is a sample musicxml file and image.
![sample-1](https://user-images.githubusercontent.com/14214856/35800045-b612a740-0a8d-11e8-87ba-0b1c470ed0e8.png)
[Sample.xml.zip](https://github.com/lenmus/lomse/files/1694729/Sample.xml.zip)

Missing notation
1) Tie  
2) Grace Notes
3) Crescendo and Decrescendo ( < , > )
4) Pedal 
5) Trill (tr)

Let me know where to start to integrate some of these.

**Comment by cecilios** [comment]
Missing notation in the sample (related to issue #26):

- Ties are already supported and displayed.
- Grace Notes are not yet supported.
- Crescendo and Decrescendo wedges: not yet supported. Probably not complex.
- Pedal: not imported and not supported. Should not be complex to support them.
- Trill (tr) marks: they are already supported. In the provided sample they are not displayed because are on grace notes.

Other issues detected in the sample:
- Octave-shift (measure 15): not imported and not yet supported. Probably not complex.
- Metronome mark: not imported but it is supported. Easy to solve.
- Measure numbers: not yet supported
- Score titles: In the latest LDP format, text paragraphs (title, sub-title, composers, etc.) are not represented as properties of the score but as real headings, paragraphs and texts in the document. Therefore, when rendering scores imported from MusicXML the titles and other related texts are ignored. It should not be difficult to add this functionality.

There are also room for a lot of improvements in layout, e.g.:
- slurs: compute the arches to avoid crossing the score or the notes.
- visual collisions between different notations.

Solving all these issues, specially the improvements in layout to get a clear score, will require a lot of work on my part and I have few free time, so do not expect to find these solved in Lomse in short time. Sorry! Any one in particular that is very important for your application?

**Comment by sensibol** [comment]
Please could you clarify what do you mean by Metronome mark? Is it the note with tempo information displayed at the beginning? If yes, it's not important for my application.

We require the following additions to the notations and layout improvements provided in Lomse in the given order of priority:

1. Crescendo/Decrescendo wedges,  
2. Slurs should not cross Score or Notes, 
3. Octave Shift measure

Can you provide a rough estimate as to when each of the feature will be available.

Thanks for the development.

**Comment by cecilios** [comment]
By "Metronome mark" I'm referring to the note with tempo information displayed at the beginning of the score.

It is difficult to provide an estimation for availability of each feature. I'm developing this on my spare time, that is not much.

My impression is that rendering Crescendo/Decrescendo wedges and Octave Shift lines is, probably not complex to do, as it should be similar to other already implemented notations. So solving both could take two-four weeks.

But slurs not crossing notes is more difficult. It is necessary to review and improve slurs layout algorithms and this requires rewriting some existing code and ideas and experimentation to develop the algorithms. It is difficult for me to estimate, perhaps two-three months.

But, as said, I develop this on my spare time. And the amount of available time for this varies greatly from one month to the next one. For instance, I have now all my agenda full and I will not have time for Lomse until the end of March. So, it is very difficult to give estimations.

Sorry!

**Comment by cecilios** [comment]
I'm closing this. For better management, I've splitted this in three issues:
• Grace Notes    -->  moved to issue #217
• Pedal          -->  moved to issue #218
• Octave-shift   -->  moved to issue #216
