### ISSUE TITLE
Adding Notation on rendered score

### ISSUE THREAD

**Issue by sensibol** [lenmus/lomse#118]
Is It possible to add additional notes over notes loaded from file. I would like functionality 
interactor->addNote(time value)
presenter-> update()

**Comment by cecilios** [comment]
Score edition is possible in two ways:

1. Edition commands. They are safe, do not require knowledge of the internal model, and support undo/redo. See https://lenmus.github.io/lomse/page-edit-overview.html for an overview. And this https://lenmus.github.io/lomse/classCmdAddNoteRest.html for an example inserting a note. After executing an edition command the model is automatically updated and your application will receive a paint event for updating the screen.

2. Direct edition API. In this case your application will be interacting directly with the internal model. You should know what you are doing; otherwise, there is a risk of corrupting the internal model and causing crashes. This API is not yet documented as I'm still thinking about the API for this and about the possible changes in the internal model for supporting the future MNX standard. The current API will imply the following steps:

```
    if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
    {
        //get the document to edit
        Document* pDoc = m_pPresenter->get_document_raw_ptr();

        //Use the document to get the score to edit
        //The next line of code is just an example, in which it is assumed that
        //the score to edit is the first element in the document. This will be always the
        //case when editing MusicXML imported files.
        ImoScore* pScore = dynamic_cast<ImoScore*>( pDoc->get_imodoc()->get_content_item(0) );

        if (pScore)
        {
            //get the instrument (score part) to be edited. In this example, I'm assuming
            //the first instrument. 
            ImoInstrument* pInstr = pScore->get_instrument(0);

            //append a note at the end, e.g. a quarter note, pitch C4
            pInstr->add_object("(n c4 q)");

            //for inserting notes or other objects it is necessary to determine the 
            //insertion point. For locating the insertion point there are
            //many possibilities, usually involving an iterator or a cursor object.
            //Current API do not consider specifying time position, although
            //it could be a possibility for future. For using time position the best
            //would be to use a cursor object:
            ScoreCursor cursor(pDoc, pScore);
            //move cursor to desired time, instrument and staff
            int instr = 0;    //assume it is the first instrument
            int staff = 0;     //assume it is the first staff
            TimeUnits timepos = 64.0f;    //whatever
            cursor.to_time(instr, istaff, timepos);
            ImoStaffObj* pAt = cursor.staffobj();        //get pointed object

            //insert the note
            stringstream errormsg;
            if (!pInstr->insert_staffobj_at(pAt, "(n e4 e)", errormsg))        //insert 8th note, pitch E4
            {
                //error. An explanation is in errormsg
            }

            //once the updates are finished, invoke close() method for
            //for updating the internal data structures
            pScore->close();      
        }
    }
```
The above example was written on the fly and is not tested. But I hope you can get an idea.

If you have a need for using the direct modification API I will have to document all this, and discuss with interested people for cleaning and completing the API.

**Comment by sensibol** [comment]
I tried the Direct edition API sample code. Could you guide me as to how to modify the above code to add a note in case a staff object is not found i.e. the cursor points to k_cursor_at_empty_place.
In such case 
`ImoStaffObj* pAt = cursor.staffobj();        //get pointed object`
pAt is nil and the insert_staffobj_at returns without adding staff object.

**Comment by cecilios** [comment]
If cursor is pointing to an empty place, you can always move it to a valid place. For instance:
```
cursor.move_next();
cursor.move_prev();
```

In any case, it is important to note that rules for music notation impose constrains on valid places (time positions) for inserting notes, rests or other objects. Therefore, it is not possible (at least in lomse) to place notes on arbitrary time positions. In fact, as in any music score on paper, time position for a note is implied by its position on the staff in relation to previous notes.

In lomse, the music is basically a list of objects (mainly notes and rests) on the staff. These objects are ImoStaffObj objects. For inserting a new staffobj you can either:
- append the new staffobj at the end, and
- insert the new staffobj before an *existing* staffobj
In both cases, the time position for the new added staffobj will be implied by the preceding staffobjs in the staff.

For instance, in lomse a quarter note lasts for 64 TimeUnits. So, for instance, in an score with three quarter notes c4, e4 and c5, note c4 is at time 0, note e4 is at time 64 and note c5 is at time 128.

If you insert a new quarter note (pitch g4) before c5 note, the the new inserted note will be at time 128 and the c5 note will be shifted to time 128+64 = 192.

If you would like that note c5 remains at time 128, then the new inserted note must be on a different voice or the inserted note should be added to form a chord.

Modifying the internal model by using the Direct edition API requires a good understanding of lomse internals, at least about the internal model organization, cursors and API methods. I will start soon to document all this but it will take some time.

Could you tell me exactly what are you trying to achieve, so that I can better guide you?
