### ISSUE TITLE
E-mail notifications for travis builds

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#129]
It's very helpful to have Travis CI configured for lomse.
When I'm doing changes to lenmus I'd like them to run through tests too, before I create a PR even. That's why I've activated Travis builds in my repository fork.

Your travis config file contains e-mail notification address:
```yml
notifications:
  email:
- s.cecilio@gmail.com
```

I think that part of config causes you to receive e-mail notifications when I'm pushing branch or commits to my fork. I would consider them spam. I cannot change the config file in my fork because such a change would be part of PR, not good.

**So here is the question:** is it necessary at all to have the e-mail address in the travis config? Travis sends e-mail notification to the commiter by default anyway.

**Comment by cecilios** [comment]
Thanks for the help.
Yes, I've noticed that I am receiving e-mail notifications when you work on this, but I didn't know the reason. Now, it is clear to me. What should I do to fix this, so that I receive notifications when I do the changes but not when other people working on this do changes? My knowledge of Travis is zero!

**Comment by hugbug** [comment]
All you need to do is to remove the notifications-section from the Travis config file.

Here is a step by step guide for very beginners 😉:
- create a new local branch from master branch;
- open `.travis.yml` in a text editor and remove the following part: 
```
notifications:
  email:
- s.cecilio@gmail.com
```
- commit the changes into local branch;
- publish the branch;
- Travis CI detects that your project has a new branch and starts building and testing it;
- you can go to travis.org, login with your github credentials and you'll see history of all builds. For your last push to repository there is a new task, which can be already running or it can be in pending state if Travis servers have much work. Usually the waiting in pending state is only few minutes. When the building starts you can see the build logs in almost real time;
- after the build (with tests) is completed you receive a email notification.

By default Travis doesn't send email notification on every commit but rather when the project needs your attention. This is handy because it doesn't bother your about successful tests. It sends notifications:
- if you publish a new branch (for any build status being it failure or success);
- if you published a breaking code and the build has failed;
- if a build was successful and the previous build has failed (you'll get a nice message "Fixed!").

The notification section in the config file allows to fine tune when and where to send notifications but I've found the default config to work perfectly.

You can experiment with this test branch by committing breaking code and checking if you get notifications. The tests runs about 10 minutes plus allow some time for the task in pending state. Once you have this tested with the test branch you can edit the config file in master branch.

There is a good documentation for the config file on Travis web site. Each change usually requires experimenting and it's a good idea to do that in a separate branch which you can delete after you have a working config file.

One useful feature of Travis is a so called test matrix where you can configure multiple test runs in different environments. For example you can test the build on different compilers simultaneously (such test tasks run independently). I do that for example to test in GCC 4.8, 4,9, 5.1 and clang 3.6. This is especially useful if you want your code to be compatible with a certain (older) compiler version whereas you develop on a newer version.

But you have written the Travis config file yourself and it works very good. I don't know if you find any new info in my post :)

**Comment by cecilios** [comment]
Thank you very much for your detailed explanation. Really helped!
I read about Travis time ago, when I set up the GitHub account for LenMus and Lomse projects. But once done, I never had to deal with travis configuration again, so I forgot everything for configuring Travis. 
To me, Travis is very useful as a double check in an environment different that my machine. But when I merge a PR I always check it in my machine, not only to double check, but because Travis script only runs unit tests but not my visual regression tests. These regression tests are very important as lomse is tested by processing near 400 scores and checking if there are differences on the generated images from the images generated with previous code.

Thank you very much for your help.
