### ISSUE TITLE
Trying to reduce or eliminate dependencies from other libraries

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#131]
I'm working on a cross platform (free and open source) music application. Currently I compile and test it on Windows, macOS and iOS. Linux and Android will be supported later.

As there is no uniform build system for these platforms adding dependent libraries is a pain. The easiest would be to just add a new library into the project source code tree. I would do that with Lomse. I obviously can't do that for boost which is extremely heavyweight. Libpng, zlib and freetype - not sure about them either.

As an experiment I've tried to remove dependencies from other libraries:
- replaced **boost** with alternatives from standard library. More on this below.
- **zlib** - I only need to display scores, I don't need Lomse to save or load compressed files. I disabled zlib related parts by commenting them out. That was easy. A proper implementation would be to introduce a preprocessor define such as `LOMSE_DO_NOT_USE_ZLIB` and disabe related code parts with `ifdef`s. This define will be disabled by default (to enable all features) but can be activated when building Lomse (or when integrating it into source code tree of other project).
- **libpng** - I also don't need Lomse to read or save png-images. I've used the similar approach as with zlib and that was easy again.
- **freetype** - I didn't have much thoughts about this yet. Probably not avoidable but who knows. Maybe Lomse could have an abstract font drawer class and the user code could provide an implementation using user code classes (for example JUCE classes in my case).

The rest of this post is about boost.

## Boost
- `boost::thread`, `boost::mutex`, etc. replaced with their analogues from `std`:
   - `ScorePlayer` uses `timed_join` and `interrupt` which doesn't exist in standard library. I do not consider this to be a big issue because:
        * ScorePlayer already implements a proper signaling for interruption;
        * external thread termination is dangerous anyway and should be avoided;
   - `std::thread` requires **C++11**.
- `boost::format` replaced with `std::stringstream`:
   - `std::stringstream` isn't that comfortable to use but it works;
   - alternatively we can write an own printf-like function using `std::vsnprintf` (requires **C++11**).
- `boost::to_upper_copy` is used once. Replaced it with own implementation using `std::toupper`.
- `boost::variant` is used once in `AttribValue`. Using `union` instead.
- `date_time` module is used for two purposes:
  - obtaining current datetime and converting it into string, mostly for logging but also as time stamp in saved files. We can use `std::time` and `std::strftime` for that;
  - for performance measurements (with microseconds precision). `std::chrono::system_clock` and `std::chrono::duration` should be a replacement. I haven't tried them yet. Requires **C++11**. Alternatively we can use C functions `gettimeofday` on POSIX and a proper replacement on Windows (platform specific code but doesn't need C++11);
- `boost::asio` has no replacement. However `LOMSE_USE_BOOST_ASIO` is `0` by default. Is this an experimental feature?

I've made the changes described above and was able to compile and run Lomse without boost. Since it was made as a proof of concept the result isn't ready to be submitted as PR.

Before I create a proper PR to remove boost dependency I'd like to clarify first:
### Is this something which can be accepted into Lomse at all?
Maybe you like boost so much or maybe you think that using boost isn't a problem at all.

### Is support for pre-C++11 compilers important/necessary?
I personally wouldn't bother in supporting pre-C++11 compilers. That allows to use new features throughout Lomse code (lambdas, for-range loops, move-semantic, etc.)

If older compilers need to be supported then there must be a switch (compiler define) to use either boost or standard C++11 library.

If support for older compilers isn't needed we can use the new features without `ifdef`s.

### Is LOMSE_USE_BOOST_ASIO experimental or a needed feature?
There is no replacement in standard library and boost is necessary for this feature and must be retained at least for this.

### What you prefer as replacement for boost::format?
`std::stringstream` or a own printf-like function?
I did use `std::stringstream` in my test. It doesn't look as pretty but works and is a native C++ feature.

------

Thanks for considering this.

**Comment by cecilios** [comment]
Thanks for your toughs.

> Is this [to remove boost dependency] something which can be accepted into Lomse at all?

Yes, no problem. Avoiding dependencies is always a good thing. And it is really a pain having to depend on so many libraries. Boost was used because some needs could not be solved in a platform independent way when I started the project. Nowadays, the c++ standard includes replacements for some boost libraries (or some boost libraries are included in c++ ;-)  ).

So, removing dependencies from Boost is not a problem. It's a gain!

> Is support for pre-C++11 compilers important/necessary?

No need to support pre-C++11 compilers. In fact current Lomse code requires C++11 or greater (see issue #95), as it was necessary to use regex and I didn't like the idea of introducing more dependencies from Boost. It would be nice to support older compilers but sooner or later they will not be supported.

> Is LOMSE_USE_BOOST_ASIO experimental or a needed feature?

It was an experimental feature to try to avoid having to relay on an external timer provided by the user application for blinking the caret. But, finally, was never used. My position on this is that it would be better not to overload Lomse with not required code. So, better remove boost asio and associated code.

> What you prefer as replacement for boost::format?

I would prefer not having to implement and maintain functions for doing things that can be done with standard functions. Take into account the costs of testing the code to avoid future problems (in particular buffer overflows and dealing with most common data types). Therefore, I would prefer to replace boost::format with standard functions such as std::stringstream. Nevertheless, if the replacement code for an own printf-like function is small and safe, this would be also an acceptable solution.

> boost::to_upper_copy is used once. Replaced it with own implementation using std::toupper.

Ok. Do not write a replacement function, but refactor the code using boost::to_upper_copy to use std::toupper instead.


> zlib

It is needed, mainly for importing files. So the solution, as you propose, would be to introduce a preprocessor define such as LOMSE_DO_NOT_USE_ZLIB and disable related code parts with ifdefs. Also, need to review behaviour when this part is disabled and Lomse is required to open a compressed file, to avoid crashes.

> libpng

Similar approach to zlib: preprocessor define and review behaviour when this part is disabled and Lomse is required to display an image.

> freetype

freetype is required for managing fonts. Rendering is done by drawer class. Currently there is an important problem for managing fonts (see issue #102) so I would suggest maintaining freetype for now and exploring a solution that could also solve #102. Perhaps platform specific modules maintained as part of the project.

**Comment by hugbug** [comment]
I'm glad you like the idea!

I'll prepare a PR for removing boost.

**Comment by cecilios** [comment]
I would prefer one PR just for threads, so that this can be tested extensively. All other changes can go in one or several PRs as you prefer.

**Comment by hugbug** [comment]
> I would prefer one PR just for threads, so that this can be tested extensively. All other changes can go in one or several PRs as you prefer.

I was going to submit a PR replacing `boost::thread` with `std::thread` but the linking of testlib has failed on Travis:
```
[100%] Linking CXX executable bin/testlib
/home/travis/build/hugbug/lomse/build/bin/liblomse.so: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/testlib] Error 1
make[1]: *** [CMakeFiles/testlib.dir/all] Error 2
```

It seems an explicit linking to pthread is needed to be defined in CMake configuration file. Since we are going to remove boost completely from the config file anyway I would rather do that changes together.

Therefore I propose the following order of changes:
- submit a PR containing all boost related changes excluding threads;
- once accepted submit another PR which replaces threads. This PR will also include changes to Make config file.

That way we can test all changes not related to threads separately first. Then, after replacing threads, the tests can be repeated for the whole boost removal campaign and will cover testing of configuration step, compiling, linking, testlib and manual tests.

**Comment by cecilios** [comment]
No problem. Do it as it is more convenient for you. My only concern is that I would like to test, if possible, threads related changes in isolation from other changes.

**Comment by hugbug** [comment]
Closing this as resolved.

**Comment by cecilios** [comment]
Thanks for all this work. Just for future reference, this issue is solved by following PRs:
- PR #144 - Replaced boost::format with standard functions
- PR #146 - Replaced boost::variant with union class
- PR #150 - Replaced boost::date_time with std::chrono
- PR #156 - Replaced boost::thread with std::thread. This PR also replaces the only instance of one instance of boost::to_upper_copy and removes boost::asio.
- PR #159 - Make dependencies from zlib and pnglib optional
