### ISSUE TITLE
Suggestion: Documentation update for realtime playback application

### ISSUE THREAD

**Issue by sensibol** [lenmus/lomse#145]
For our application, we are playing recorded audio (instead of Midi events) along with score display in Lomse, We noticed a lag between sound from speaker and note highlight in lomse. This was due to score being loaded in player in the play method. 
https://lenmus.github.io/lomse/sound-generation.html#how-to-play-score

For realtime application, when playing back audio, it would be better to load score in ScorePlayer when the file is opened. The below functions should be moved to opening a file.
```c
 pPlayer->load_score(pScore, NULL);
```
Play method should have
```c
- (void) play{
    if (!m_pPresenter) return;
    if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
    {
       //Do proper error handling  ensuring pScore is not NULL
        long nMM = 80;                  //beats per minute
        //start playback
         m_pPlayer->play(k_do_visual_tracking, nMM, spInteractor.get());
    }
}
```

**Comment by cecilios** [comment]
Method `pPlayer->load_score()` main responsibility is building the midi table. Building this table is only necessary when the score is going to be played back. Your application can always invoke this method after opening the score. Therefore I do not see the need to integrate the code and force all applications using lomse to build always the table, as in some cases/applications this table will never be used.

As to your approach, relaying on audio instead of MIDI, I see a drawback: how is going your application synchronize the midi player tempo with the audio player? Currently, Lomse doesn't have an API for this synchronization. Take into account that any small differences in tempo between both players will create delays of one or more beats after a certain number of measures! It would be necessary to design a way to synchronize lomse score highlight, and implement it. 

If I misunderstood something of your proposal, please let me know.
