### ISSUE TITLE
Equal width measures

### ISSUE THREAD

**Issue by sensibol** [lenmus/lomse#165]
I would like all the measures to be of equal width. Does the layouter support this? If so, please share the code to get the above behavior.

**Comment by cecilios** [comment]
I'm not sure if you would like equal measures per system or for the full score. In any case, current layout algorithm does not support measures of equal size.

Implementing this would require a two steps approach: first the current algorithm and then a second one to re-layout everything but forcing measures length to the maximum width detected in first step. It should not be complex to implement but I do not see the need. Good quality manually engraved scores never have equal size measures, as measure length is adjusted to its music content. Using equal size would be as forcing a text editor to use the same width for every word.

Why do you need this?

**Comment by sensibol** [comment]
For my application I need to have a scrolling sheet music. I am doing this by updating the viewport using an external thread at regular interval (uniform scroll). If the measures are uniform, I would not require to ensure the current highlighted measure is within the viewing area. They would inherently lie within the viewing area.

My application does not deal with repeating segments or tempo changes in between score. So for me this trivial scrolling works.

Will work from your suggestion and make updates to layout algorithm.

**Comment by cecilios** [comment]
> I would not require to ensure the current highlighted measure is within the viewing area. They would inherently lie within the viewing area.

From your explanation I understand that highlight will be controlled by MIDI player. In this case Lome will send update viewport events to ensure that the current highlighted measure is within the viewing area. Therefore, you don't need additional code.

A different issue is that you would like that the score be always slowly scrolling instead of scrolling in jumps from time to time. If this is the case, perhaps a better solution could be designed and implemented in Lomse without the need to force to use equal width measures and that will work also when there are tempo changes and repeats.

**Comment by cecilios** [comment]
Closing as wontfix; if there's any further thoughts on this issue feel free to comment here - if there's enough demand for this it can be reconsidered.
