### ISSUE TITLE
Cannot dowload "The Lomse Hacking Guide"

### ISSUE THREAD

**Issue by iomeone** [lenmus/lomse#205]
Cannot dowload The Lomse Hacking Guide from [documents  page ](http://www.lenmus.org/en/lomse/documents )

**Comment by cecilios** [comment]
The "Lomse hacking guide" was totally outdated and not maintained for several years. Taking advantage of the web update, I have:
- Deleted no longer maintained pages, such as the "Lomse hacking guide" pages, and
- Moved all Lomse and wxWidgets still relevant pages to their respective projects on Github.

Now, in the website, there is only information about LenMus Phonascus.

However, some deleted pages are still accessible through the old URLif you know it, since they have not been deleted from the server. That is the case of the URL you mention, but some the refered documents on it are no longer available. And others are available in GitHub repo.

**Comment by iomeone** [comment]
ok, I found https://lenmus.github.io/lomse is what I am looking for! Thanks~
