### ISSUE TITLE
Crash with certain musicxml files

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#223]
I have two musicxml-files which cause crashes in the Lomse code.

Both files were created with MuseScore via importing of MIDI-files. Therefore these score files are far from what a living soul would make ;)

In my somewhat older version of Lomse (last updated Sep. 2019) I was able to fix the issue with [this two line commit](https://github.com/hugbug/conpianist/commit/60def42b7dd48745ceff4cdbdbf6aee7d8ada25f).

Interesting, the current version of Lomse has other code places causing troubles with these two score files. The following commit contains other fixes, needed to load and display the score without crashes in current Lomse version - [commit with more fixes](https://github.com/hugbug/conpianist/commit/f600be44986c658fceee724d2c2b1f0ca128055b).

Most likely the changes I made are not a proper way to fix the underlying issues. Therefore I'm not sending a PR.

## Files causing troubles
[Murka.musicxml.zip](https://github.com/lenmus/lomse/files/4464651/Murka.musicxml.zip)
[Can You Feel The Love Tonight-017.musicxml.zip](https://github.com/lenmus/lomse/files/4464652/Can.You.Feel.The.Love.Tonight-017.musicxml.zip)

## More info
I can provide stack traces in a case you can't reproduce the crashes.

**Comment by cecilios** [comment]
Thanks for reporting and for the fixes. I will investigate this.

File _Can You Feel The Love Tonight-017.musicxml.zip_ does not crash in my test app. It just displays this error:
![error](https://user-images.githubusercontent.com/5238679/79045938-23c94200-7c0e-11ea-91d8-b3f7a760e75d.png)

This app is using `k_view_vertical_book`. Which view type is using your app?

The other score crashes in one of the places you fixed:
https://github.com/lenmus/lomse/blob/eb41639fc2fb68afd9e118a8e0fb8e44d7bf6f2a/src/graphic_model/engravers/lomse_articulation_engraver.cpp#L255

The problem is to determine why `minValue.second`  is `nullptr` and fix the code to prevent this. I will investigate.

**Comment by hugbug** [comment]
I'm also using k_view_vertical_book.
The error you get is because the score contains many instruments but the window height isn't large enough. I'm getting this message too if the window is too small. That's not relevant to the issue.

If you can make the window bigger so that the drawing code starts to execute, you should be able to reproduce the crash.

Thanks for looking into this!

**Comment by cecilios** [comment]
> If you can make the window (the page height) bigger so that the drawing code starts to execute, you should be able to reproduce the crash.

Thanks. I will check.

**Comment by cecilios** [comment]
Score _**Murka.musicxml**_ renders without crashes with the patches you send me. See my comments at https://github.com/hugbug/conpianist/commit/f600be44986c658fceee724d2c2b1f0ca128055b#commitcomment-38434172

With the latest code in my local repo, score _**Can You Feel The Love Tonight-017.musicxml**_ renders without crashing if I increase paper height. I've noticed that I have a lot of commits not pushed into main branch. I will prepare a PR in a few days to push my commits. Before updating the lomse sources in conpianist pay attention to a couple of issues:

- **Fonts and font management**. Finally, I addressed issue #102 and now lomse is not totally platform independent. For Linux (and macOS), current approach is to use _fonconfig_ library to determine font file to use and do font substitutions. But this creates a dependency from _fontconfig_ library. I have not tested in macOS and I don't know if the dependency from _fontconfig_ is acceptable. If not, a configuration macro could be added for selecting the old behaviour in any platform without depending on _fontconfig_.

- **Logs**. Lomse logs were polluting the system. This has been fixed and now log files are created at user home folder. They are useful for debugging crashes or other issues. I've noticed that you also had this problem and applied an ad-hoc patch to supress the logs ( https://github.com/hugbug/conpianist/issues/32 ). The comming PR will override your patch.

Finally, I would like to comment that I created this library by splitting my application. The idea was that all this complex code to render scores could be freely available to other applications. Therefore, I will certainly consider any comment, sugesstion or change that could facilitate the use of lomse in your code, as this will also simplify things for future users. Do not hesitate to ask for changes.

**Comment by hugbug** [comment]
Thank you very much.

Maybe you can reproduce one more issue with "Can You Feel The Love Tonight-017.musicxml" which I have in my app?

I make the page height big enough for the score to display. The first page is displayed correctly but when I scroll to the second page I get the message "Not enough space for drawing...". I'm trying to increase the page height and then I can get the second page displayed correctly too but the error is then displayed on the third page. Now regardless on how big I make the page height the third page can't be displayed (with the same error message rendered on the image).

With the older version of Lomse this issue did not occur (I have retested to confirm this).

My changes to `lomse_box_score_page.cpp` were related to this issue. In my app the current song position is marked in the score with the tempo line. If the line is moved to the page which cannot be rendered a crash occurs (see callstack on the left):

![Screen Shot 2020-04-11 at 22 08 50](https://user-images.githubusercontent.com/3368402/79053910-327d1c80-7c41-11ea-926c-8b73336343f4.png)

**Comment by cecilios** [comment]
yes. I noticed this. To fix this comment out this line:
https://github.com/lenmus/lomse/blob/master/src/graphic_model/layouters/lomse_system_layouter.cpp#L188

**Comment by cecilios** [comment]
> My changes to lomse_box_score_page.cpp were related to this issue. In my app the current song position is marked in the score with the tempo line. **If the line is moved to the page which cannot be rendered** a crash occurs (see callstack on the left)

But "why the page cannot be rendered" ? Because these other bugs?

**Comment by hugbug** [comment]
With "page cannot be rendered" I mean the message "Not enough space for drawing..." rendered on the page. For some reason the message is drawn on second and third pages but the first page is rendered OK. I don’t think this issue is related to other crashes.

I haven’t tried the proposed fix with commenting out line 188 yet.

**Comment by hugbug** [comment]
> yes. I noticed this. To fix this comment out this line:
> https://github.com/lenmus/lomse/blob/master/src/graphic_model/layouters/lomse_system_layouter.cpp#L188

That did the trick. Thank you. Is this a proper fix (which you'll apply too) or are you going to investigate this further?

**Comment by cecilios** [comment]
I will investigate more but it will take some time because first I have to isolate a minimal portion of the score displaying this error and then I have to debug the problem and it is a complex task with posible additional implications.

The commented line is part of a collection of changes for dynamically allocating the space between staves so that symbols in one staff do not collide with symbols in the next one. If you comment out that line the spacing will be a fixed amount, as it was until recently.

As to the fixes in  `lomse_box_score_page.cpp` I would prefer not to include them. They do not harm but will hide bugs if execution arrives there and the collection is empty. It should not!

**Comment by hugbug** [comment]
Thank you for the explanation.
I appreciate your hard work!

**Comment by cecilios** [comment]
This issue is finally fixed but the PR will take some days.

- Commit https://github.com/cecilios/lomse/commit/5c2aa7238bfee2e57c5a62b0e62a04f198b258ac are your initial fixes, revised.

- Commit https://github.com/cecilios/lomse/commit/b3c2f2b4c2d32040fad74b8f3efaa91a2175ad62 fixes the error that caused the lack of space for rendering the system. The problem is due to accumulation of staves displacements for avoiding collisions. It didn't manifest during tests because I used short scores. After applying this patch you can restore the commented out line in 
https://github.com/lenmus/lomse/blob/master/src/graphic_model/layouters/lomse_system_layouter.cpp#L188

- Commit https://github.com/cecilios/lomse/commit/be883dfd441afceb0001f2bdced5334a581da933 changes the behaviour when not enough space for displaying one system in the page. Instead of displaying the error message, now the system is anyway displayed, overrunning the paper. 

There are still some issues with sample *_Can You Feel The Love Tonight-017_*: in one page, towards the end, the renderization is really strange. I have to investigate this.

There is also an issue with the right barline: it is not aligned with staff lines. But this is not related to #223. I would like to fix it before preparing the PR with all cumulative changes and the fixes for #223 and for this barlines issue. So it will take a few days.

**Comment by cecilios** [comment]
Commit https://github.com/cecilios/lomse/commit/97cad6639df6fce6736a75584321f6b1d593a144 fixes the strange behaviour detected in measure 51 of sample *_Can You Feel The Love Tonight-017_*.
