### ISSUE TITLE
lomse_other.cpp probably needs font caching too

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#231]
On Mac I use `lomse_other.cpp` and I encountered that the log is polluted with `FontSelector::find_font`:
```
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=en, name=Liberation serif
lomse_other.cpp, line 103. INFO: [lomse::FontSelector::find_font] --- Path=/Users/User/ConPianist/Builds/MacOSX/build/Debug/ConPianist.app/Contents/Resources/fonts/LiberationSerif-Regular.ttf
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=en, name=Liberation serif
lomse_other.cpp, line 103. INFO: [lomse::FontSelector::find_font] --- Path=/Users/User/ConPianist/Builds/MacOSX/build/Debug/ConPianist.app/Contents/Resources/fonts/LiberationSerif-Regular.ttf
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=en, name=Liberation serif
lomse_other.cpp, line 103. INFO: [lomse::FontSelector::find_font] --- Path=/Users/User/ConPianist/Builds/MacOSX/build/Debug/ConPianist.app/Contents/Resources/fonts/LiberationSerif-Regular.ttf
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=en, name=Liberation serif
lomse_other.cpp, line 103. INFO: [lomse::FontSelector::find_font] --- Path=/Users/User/ConPianist/Builds/MacOSX/build/Debug/ConPianist.app/Contents/Resources/fonts/LiberationSerif-Regular.ttf
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
lomse_other.cpp, line 64. INFO: [lomse::FontSelector::find_font] lang=any, name=Bravura
```
and so on. About 15000 log entries after loading one MusicXML-file.

All caused by `LOMSE_LOG_INFO`. The Linux and Windows versions use caching and do logging only when not in cache.

Either remove logging or add caching to `lomse_other.cpp` too. I think caching is more appropriate because under certain circumstance the search involves calls to Lomse Doorway and potentially expensive file search in file system.

**Comment by cecilios** [comment]
I no longer use this file and seting up a test program would cost me some time. I don't like the idea of updating the repo with this untested version, so I'm commiting the changes to my fork. You can download the new version from here:
https://github.com/cecilios/lomse/blob/changes/src/platform/lomse_other.cpp

As you uses this file, could you please test it and tell me if the changes are ok and solve your needs? If not, could you please send a PR with the changes (tested)?

By the way, have you tried the Linux platform version using fontconfig? If it is not suitable for your needs, I would appreciate an explantion to understand the reasons, as that might help me to take into consideration other library use cases. Thank you.

**Comment by hugbug** [comment]
Thank you. That fixed the issue.

I use `lomse_other.cpp` on Mac because when I tried `lomse_linux.cpp` the `fontconfig.h` wasn't found. The name `linux` suggested the file was specific to Linux. I haven't bothered further. The `lomse_other.cpp` worked fine after all.

I also wasn't aware of benefits of using fontconfig. I still don't know that the benefits are. I need to supply Bravura with my app anyway, right? Then it doesn't mater if I supply Liberation too.

I gave another try to fontconfig on **MacOs** and it does work. I just needed to configure proper include and libraries paths in my project file.

My app can also be compiled for **iOS** and the things are different there. There is no fontconfig included in the iOS SDK. I most likely can compile it like I did with freetype. But why bother?

---

Maybe `lomse_linux.cpp` should be renamed to `lomse_unix.cpp` or `lomse_posix.cpp` to avoid  confusion?

**Comment by cecilios** [comment]
> That fixed the issue.

Ok, thanks for testing it.

> I also wasn't aware of benefits of using fontconfig. I still don't know that the benefits are. 

It solves two problems:
- It knows were are the fonts installed. Take  into accound that there are several places to look for: system wide installed fonts, local installed fonts, user specific fonts, etc. FontConfig will tell the app (lomse in this case) the path for the desired font file. And this is platform dependent. Lomse cannot duplicate that code.
- When a font is not installed, the app (lomse) should do a good substitution for it. For instance, if you ask to use Garamon and it is not installed, the app (lomse) should use the most similar installed font  instead of reporting erros or crashing. The substitution tables can be huge but font config provides this service.

> I need to supply Bravura with my app anyway, right?

Yes, unless lomse uses fontconfig and Barvura is already installed.

>  But why bother?

Currently there is litlle or no gain for your app. because texts in MusicXML normally uses fonts that lomse_other.cpp can replace. But  you could find scores using fonts that lomse will neither recognize nor support. Probably using fontconfig is not a priority for your app. but in future, when the app. is finished and you'd have time for polishing it, IMO using fontconfig should be considered.
