### ISSUE TITLE
Compiling in Windows using MinGW

### ISSUE THREAD

**Issue by de5car7es** [lenmus/lomse#235]
Hi

Having hard time compiling using MinGW.
First. generating makefiles had problem with if(CMAKE_NO_STD_NAMESPACE), for some reason this check fails, although I do have std. Anyway I've commented this out and created the makefiles.

The problem now is that make fails on\libs\Lomse\include/lomse_events_dispatcher.h:49:14: error: 'thread' in namespace 'std' does not name a type  49 | typedef std::thread EventsThread;

and some other similar errors on mutax.

I have installed mingw32 pthreads but it doesnt work.

Were you able to successfully compile it using MinGW ?

**Comment by cecilios** [comment]
No, sorry. I never compiled the code using cmake in Windows, neither using windows tools nor MinGW. I only build the library in Linux and cmake buils the makefile withou problems. But in windows I use lomse including its sources in my app. LenMus, therefore I never tried cmake there. Probably it needs some fixes to build in Windows. The cmake file for lenmus, at https://github.com/lenmus/lenmus/blob/master/CMakeLists.txt builds the app using lomse sources in Windows under the ubuntu subsystem.

**Comment by cecilios** [comment]
### Lomse build instructions for Windows 10

PR #236 partially fixes cmake script for building in Windows, as I explain here.

To build in Windows, open a Command Window appropiate for x64 build: _"x64 Native Tools Command Prompt"_

Create build directory:
```
cd path\to\lomse
rmdir build-area /S /Q
mkdir build-area && cd build-area
```
    
Create makefile and build:

- For building the static library:

```
cmake -G "Ninja" ..
ninja
```

You will see many warnings, mainly complaining about usafe function, such as:
> 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.    

There are also a couple of other warnings that I have to fix.

The unit tests runner program `testlib.exe` is built and is linked against zlib.lib and libpng.lib but when executed, the testlib.exe program complains of not finding `zlib.dll` and `libpng.dll` (!!!???). Copying these DLLs to build folder solves the problem and the tests run. There are four failures related to Chinese font.

To install the library and the header files it is required to have admin privileges. To do it, open as admin a _"x64 Native Tools Command Prompt"_. Then:

```
cd path\to\lomse\build-area
ninja install
```


- For building the shared library:

```
cmake -G "Ninja" -DLOMSE_BUILD_STATIC_LIB=OFF -DLOMSE_BUILD_SHARED_LIB=ON ..
ninja
```

In this case, the library is built but building the unit tests runner program fails due to linkage problems. I do not know how to fix this. 

My knowledge of Windows and cmake is very limited, and I never used MinGW. Any help for fixing all this will be greately appreciated!

**Comment by chxiaoxn** [comment]
I have a successful build using this:

```
mkdir build
cd       build
cmake -G "Unix Makefiles" ..
make
```
The `localtime_r` is the only issue, I just turned into `localtime_s` and it worked.

**Comment by cecilios** [comment]
Glad to know and thanks for reporting. My understanding is that to build for MinGW you will need MinGW installed and available in your %PATH%. Then do:
```
mkdir build
cd build
cmake -G "MinGW Makefiles" ..
make
```
Why are you instead generating Unix makefiles?

**Comment by chxiaoxn** [comment]
> Glad to know and thanks for reporting. My understanding is that to build for MinGW you will need MinGW installed and available in your %PATH%. Then do:
> 
> ```
> mkdir build
> cd build
> cmake -G "MinGW Makefiles" ..
> make
> ```
> 
> Why are you instead generating Unix makefiles?

Thanks for so replying so quick. 
I think in MinGW, unix makefiles are the same with makefiles. Later, I figured out that if I use `cmake -G "MinGW Makefiles"`, I have to use a long `mingw32-make` to make. This previously I did not know.

**Comment by cecilios** [comment]
I never used MinGW but my understanding is that it is for building Windows binaries using linux tools. If you uses `cmake -G"Unix Makefiles" ..` and builds with gcc I think that you will be generating linux binaries and they will not be valid. But this is just my uninformed understanding. I never had to learn and deal with MinGW.

If you would like to generate Windows binaries perhaps it is simpler to do it without using MinGW, as I explained here https://github.com/lenmus/lomse/issues/235#issuecomment-626874538

**Comment by cecilios** [comment]
Closed, inadvertely, in PR

**Comment by cecilios** [comment]
Closing this issue due to lack of any concrete implications.
