### ISSUE TITLE
How do?

### ISSUE THREAD

**Issue by hdhxt11** [lenmus/lomse#258]
Hi:
How to make the rendered image positive?(save to file ,not to screen)
What if I rendered an image as wide as the screen?

Thank you!

**Comment by cecilios** [comment]
> What if I rendered an image as wide as the screen?

Lomse follows the **Model-View-Controller** architecture. Internally, it maintains a model for the full score (the graphic model) and it is rendered on a bitmap to display parts of it or the whole model. Is up to you application to decide what to display. Please, see https://lenmus.github.io/lomse/page-render-overview.html

Normally, to display a long score the user of your application will do scrolling. As the screen is scrolled, your application has to request lomse to display the relevant part. It is your application who controls and decides what to display. For instance, tutorial 2 (https://github.com/lenmus/lomse/tree/master/examples/tutorials/tutorial-2-wx) is an example of how to drag the score with the mouse and display other parts or pages. But, in any case, the approach for this is not some specific lomse approach, it is the model-view approach common to many many applications.


> How to make the rendered image positive?(save to file ,not to screen)

You can save the score in different formats, such as textual (e.g. MusicXML or LDP) or graphic (e.g. PDF, bitmaps or images). But lomse does not have yet fully developed, ready to use, exporters for this.

Currently, the more developed exporter is not for MusicXML format but for LDP and LMD formats. But it is not complex to develop a MusicXML exporter. If you are interested in this I could give you some orientations and help. Of course I accept PRs and collaboration to do it. Exporters to other formats or languages could be developed and should not be too complex, but I do not have time for this. Current existing exporters are easy to use, it is just including the appropriate header file

```
#include "lomse_ldp_exporter.h"

ADocument doc = m_presenter->get_document();
ImoDocument* pRoot = doc.internal_object()->get_im_root();

LdpExporter exporter(&m_libraryScope);
exporter.set_remove_newlines(true);
string source = exporter.get_source(pRoot);

//now save "source" in a file
```

If you would like to export your scores as images (perhaps to bundle them in a PDF) it is your application who must do it. The approach is the same than for displaying on the screen: provide lomse a bitmap big enough for a whole page, ask lomse to fill it with the desired page, save the resulting bitmap, and loop for all the pages. And when finished, a simple script could bundle all images in a pdf. The example code for printing and score (https://lenmus.github.io/lomse/page-printing.html) does something analogous but sends the bitmaps to the printer instead of saving then to a file.

Please, take into account that Lomse provides the engine to render scores but it is your application who decides what to render and what to do with the renderizations.

**Comment by hdhxt11** [comment]
Hi:Take a look at the picture below:
![image](https://user-images.githubusercontent.com/70871833/97508630-0fd30b00-19bb-11eb-9755-3b79380737f9.png)
1.at right of  image, is filled gray ,how make all background is white?
2.after render ,before copy it to screen use function bitmap::draw(dc)
   the score is inverted,how make it to positive

**Comment by cecilios** [comment]
### Reversed image in Windows

Using Lomse in Windows is the most difficult case due to having to create an specific class to manage bitmaps. In all other platforms you don't need this, as there are suitable alternatives and you don't nee to create your own bitmap class. I'm not sure what is the problem in Windows but look at this issue about that problem: https://github.com/lenmus/lomse/issues/97

### Using Lomse in JUCE

I have no experience using JUCE and have never tested Lomse in JUCE. But Lomse has been used in JUCE it and I have seen it is used as follows:

```
Application framework:    JUCE
Operating system:    any


Lomse library initialization
---------------------------------------

    //Resolution: 96 * UI scale
	m_scale = m_settings.zoomUi * Desktop::getInstance().getDisplays().getMainDisplay().scale;
	int resolution = int(96 * m_scale);
	
	//pixel format
	int pixel_format = k_pix_format_rgba32;

	//Lomse default y axis direction is 0 coordinate at top and increases
	//downwards. For JUCE the Lomse default behaviour is the right behaviour.
	bool reverse_y_axis = false;

	//initialize the Lomse library with these values
	m_lomse.init_library(pixel_format, resolution, reverse_y_axis);


Creating the rendering buffer
------------------------------

    //Memory for the bitmap:    juce::Image
    //Bitmap format:            juce::Image::PixelFormat::ARGB

	m_docScale = imoDoc->get_page_content_scale(); //scale is computed by lomse when rebuilding the GraphicModel

	//create image to fit the whole page
	m_image.reset(new juce::Image(juce::Image::PixelFormat::ARGB,
		int(width / m_docScale), int(height / m_docScale), false, SoftwareImageType()));
		
	//creates a bitmap of specified size and associates it to the rendering
	//buffer for the view. Any existing buffer is automatically deleted
	juce::Image::BitmapData bitmap(*m_image, juce::Image::BitmapData::readWrite);
	m_rbuf_window.attach(bitmap.data, m_image->getWidth(), m_image->getHeight(), bitmap.lineStride);


Paint event
-----------------

void MyWindow::paint(Graphics& g)
{
	if (m_presenter && m_image)
	{
		g.drawImage(*m_image, 0, 0, getWidth(), getHeight(), 0, 0, m_image->getWidth(), m_image->getHeight());
	}
	else
	{
		String text = "Some error message";
		juce::Rectangle<int> rec(20, 80, getWidth() - 40, getHeight() - 100);
		g.drawFittedText(text, rec, Justification::centredTop, 100, 1);
	}
}

```

### Change background color

You can change View background color at any moment before a repaint event:
```
spInteractor->set_view_background(Color(255,255,255));
```

If it is just an initial setting that you are not going to change, do it for instance, at initialization, when setting the rendering buffer:
```
spInteractor->set_rendering_buffer(&m_rbuf_window);

//register to receive desired events
spInteractor->add_event_handler(k_update_window_event, this, wrapper_update_window);
...

//set initial viewport and scale
//spInteractor->new_viewport(-m_xMargin, -m_yMargin, k_no_redraw);
//adjust_scale_and_scrollbars();

spInteractor->set_view_background(Color(255,255,255));
```

I'm quite busy now, but this weekend I will try to write some documentation about your previous question on how manage the View and to display the full score, and I will tell you.

**Comment by hdhxt11** [comment]
With your help, I solved the background, inverted.
Next, I'll try to solve agg::bitmap->juce:image.
Thank you!

**Comment by cecilios** [comment]
I  found time and have updated the API documentation to add more information about how to control what to display. Please see https://lenmus.github.io/lomse/page-coordinates-viewport.html#viewport-concept

**Comment by hdhxt11** [comment]
Looking forward to your DOC.
Just now, the rendering was successfully completed in JUCE in win10 using the code you provided!
Thank you very much!

**Comment by cecilios** [comment]
I will not send you a document. I just thought about writing some texts to explain how to control what is displayed. And I have included this in the API documentation by updating the section about the Viewport concept.

**Comment by cecilios** [comment]
I am closing this issue as it appears to be resolved. If you believe things are still unresolved please let me know and I can reopen if needed.
