### ISSUE TITLE
Opening QT tutorial project

### ISSUE THREAD

**Issue by interspdev** [lenmus/lomse#271]
I downloaded the Lomse codebase and immediately opened the QT project file in QT Creator. The location for this file is: \lomse-master\examples\tutorials\tutorial-1-qt. I built and ran the project from within QT Creator and received the following error:

> error: liblomse development package not found

I then tried running CMake to build and install Lomse. After struggling with getting all the needed dependencies, I finally got CMake to run successfully at which point I tried running the QT project again from QT Creator. Unfortunately I got the same error mentioned above. Am I missing some detail? My .pro file looks like this:

```
 QT += core gui
    greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

    CONFIG += link_pkgconfig
        CONFIG += c++11
    PKGCONFIG += liblomse

TEMPLATE = app
TARGET = tutorial-1-qt
INCLUDEPATH += .

DEFINES += QT_DEPRECATED_WARNINGS

HEADERS += tutorial-1-qt.h
SOURCES += tutorial-1-qt.cpp
```

Also, can I possibly use Lomse without running CMake first? Like, say for example, dropping all of the header and source files into my Visual Studio solution directory or QT project directory and just calling Lomse functions like I would functions from any other included file? 

Thanks for any advice!

**Comment by cecilios** [comment]
> error: liblomse development package not found

For building the samples you first have to build and install the lomse library. Did you install it? It is necessary to do `make install`

I'm afraid I can not help with Qt and .pro file. I'm not familiar with Qt. But it is perfectly possible to avoid having to build the library by, as you guessed, dropping all sources and include files in your project. You will have to add also the sources from folder 'packages'.

In your Visual Studio or Qt project you will have to specify to link your project with the libraries required by lomse (freetype, etc). Also you will have to specify additional search paths for include files, pointing to the header files for the required libraries. I cannot give you more details because I do not use Windows but for developing and testing the library I have a project with this same setup, with all lomse sources included in the project.

My search directories include these
./include
./src/agg/include
./packages/utfcpp
./packages/minizip
./packages/

And for external libraries (sorry, Linux paths):
/usr/include   (here are all the dependencies installed)
/usr/include/fontconfig

As to project configuration I use pkg-config tool instead of coding paths and flags by hand:
`pkg-config --cflags libpng`
`pkg-config --cflags freetype2`

And for linking:
`pkg-config --libs zlib`
`pkg-config --libs libpng`
`pkg-config --libs freetype2`
`pkg-config --libs fontconfig`

Nevertheless, although the first lomse installation in Windows is painful due to the problem with installing the dependencies, once done it is better to use lomse as a library than having to include all its sources in your project. In both scenarios the problematic part is installing lomse dependencies and determining were are they installed. And additional problem with MS Windows (in both scenarios, installing the library or dropping its sources in your project) is the Windows requirement that when linking, all the dependencies need to be build with the same flags (I'm here referring to the  MT, MTd, MD and MDd flags). For me this always was a nightmare forcing me to having to build every dependency to ensure that all were built with the same flags. This has nothing to do with lomse, it is Windows friendliness!

**Comment by cecilios** [comment]
I am closing this issue as it appears to be resolved. If you believe things are still unresolved please let me know and I can reopen if needed.
