### ISSUE TITLE
Notes don't appear

### ISSUE THREAD

**Issue by AlbertFarguell** [lenmus/lomse#374]
After compiling tutorial-2-wx, everything went right and the program executed as expected. But after switching off and on the computer, the program executes again but this time not showing the notes, only the staff and the beams. Do you know what I am missing.
Thank you in advance,
Albert Farguell

**Comment by cecilios** [comment]
I can not reproduce this. After switching off the computer and restarting, the already built tutorial works perfectly for me.

If the staves, stems and barlines are correctly rendered the problem is for sure that lomse cannot find the Bravura font needed to render noteheads and other musical symbols. Probably lomse is not correctly installed or somehow the Bravura font was deleted.

In your home folder you will find the lomse log file `lomse-log.txt` with information logged in last execution of a program using lomse. In the log you will find a line such as:
```
lomse_linux.cpp, line 169. INFO: [lomse::FontSelector::find_font] key=anyBravura00, Path=/home/cecilio/.local/share/fonts/Bravura.otf
```

displaying the path where lomse is looking for the font. Check if the font is still installed in that path.
