### ISSUE TITLE
Duplicated definitions prevent build

### ISSUE THREAD

**Issue by jamescauwelier** [lenmus/lomse#63]
Hi!  I've been trying to get this project to build and had several issues:

- first mainly defining proper locations of libraries
- bug in zlib described [here](http://stackoverflow.com/questions/22705751/cannot-open-include-file-unistd-h-no-such-file-or-directory) for which I implemented the suggested fix
- files had been removed almost exactly a year ago (agg) that were preventing a proper CMake config.

After this CMake runs successfully and I can open the configured project in Visual Studio 2015.  But when building the project I get these errors:

![build-errors](https://cloud.githubusercontent.com/assets/1190043/22301281/c93a7914-e32a-11e6-8972-168187b3fcc6.png)

I am trying to have the library build so that I can include it in a mixed reality game for the meta2 headset.  

Any help or pointers are appreciated!  I am very inexperienced with building, especially on Windows so please understand if these are obvious problems I should be able to fix on my own.

**Comment by jamescauwelier** [comment]
If I build only the static lib I get the following errors.  Hope somebody can help me understand.

![only-static-build](https://cloud.githubusercontent.com/assets/1190043/22302660/03b7c88a-e330-11e6-9c16-b1b0d78c42bc.png)

**Comment by cecilios** [comment]
Thanks for reporting.

I'm not sure if I will be able to help in this. I no longer own windows machines and so I stopped developing for Windows long time ago. Also my knowledge of building in Windows has vanished! I'm sick and tired of Microsoft! The CMake script has been tested only in Linux. The code in CMakeLists.txt to build for Windows is just tentative code, and I never tested it. So, for sure, it is incomplete and has errors.

So, as I cannot reproduce the errors and do tests in my machine, I'm afraid that the only support I could provide is to share with you my thoughts about possible problems' origin and possible things to fix.

1. **first mainly defining proper locations of libraries**
	All libraries are located by cmake function 'find_package()'. Depending on the library to find, the code for doing it is part of cmake or it is an script in folder ./cmake-modules.  Probably you are having problems with these modules because I thing they are only prepared for Linux. In this case, the code in these modules has to be fixed for including standard locations in Windows.
	Which libraries can not be found?

2. **bug in zlib described here for which I implemented the suggested fix**
    Does your fix work?

3. **files had been removed almost exactly a year ago (agg) that were preventing a proper CMake config.**
	A year ago I updated agg files to the latest version. 
	All sources used by Lomse are listed in file ./add-sources.cmake and is updated. This file is common to Linux and Windows.
	Reviewing this file, in line 198, I see that for Windows file ./src/agg/src/platform/win32/agg_win32_bmp.cpp is required but is no longer in the repo. Has to be restored.
	Any other file for which you get missing errors?

As to the errors reported in your second post I have no idea of what are they.

Hope this helps.

**Comment by cecilios** [comment]
I think Windows file ./src/agg/src/platform/win32/agg_win32_bmp.cpp is really no needed. Better remove it from ./add-sources.cmake

**Comment by jamescauwelier** [comment]
Thank you for answering @cecilios !  

Problem 1, 2 and 3 have been fixed I think.  The issues I am still observing seem to be related to the following:

http://stackoverflow.com/questions/15421254/already-defined-in-obj-no-double-inclusions

Does that help you in understanding what might be going on here?

I hate windows as much as you do.  I am a mac user, but the hardware I'm using only works on windows.

**Comment by cecilios** [comment]
According to this:
http://lists.boost.org/boost-users/2015/04/84105.php

the solution could be adding symbol BOOST_ALL_DYN_LINK:

    -DBOOST_ALL_DYN_LINK

**Comment by jamescauwelier** [comment]
I was able to compile on windows.  The changes necessary for this are in the following commit.

https://github.com/jamescauwelier/lomse/commit/6eef54f1e23355121239ac2e235a2c526f1d92b8

I don't know if this compiles on other platform or if you even want this to be committed so I'll leave it to you to make that decision.

**Comment by cecilios** [comment]
Thanks James. I would like that the library could be built for any platform, Windows included. So I would appreciate your help for fixing the issues you found for building in Windows.

The only changes in your commit is uncommenting and changing the values of some options related to the Boost libraries. But this seems not enough for fixing the issues you reported. I only can relate this change to the duplicated Boost symbols issue, but this is just a guess. So I would appreciate an explanation about the solutions four the issues found. In particular:

- did you finally removed file ./src/agg/src/platform/win32/agg_win32_bmp.cpp from file ./add-sources.cmake, or added additional files to the sources ?

- How did you fix the issues with zlib? (C1083: Cannot open include file: 'unistd.h': No such file or directory). The link you include suggests several alternatives.

- The issue related to 'mainly defining proper locations of libraries', how was it solved ? Is there anything to be fixed in CMakeLists.txt of in the cmake modules in folder ./cmake-modules ?

I would appreciate your help so that I could fix whatever is necessary in Lome.

Thanks!
