### ISSUE TITLE
Score highlight does not work in some scores

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#70]
The score highlight does not work when playing as an attached MusicXML file.

[bach-invention.zip](https://github.com/lenmus/lomse/files/1294628/bach-invention.zip)

**Comment by cecilios** [comment]
Ok. Problem confirmed.

**Comment by cecilios** [comment]
Juuk, issue 70 is now solved.

I've noticed that you are not watching the lomse repository. If you would like to get notifications of new and solved issues, pull requests, and merges you will need to watch the Lomse Github repository. Otherwise you will not get any notifications about fixes and changes in the repository, only those related to the issues you opened.

Just go to the main page of the repository (https://github.com/lenmus/lomse) and click on the "Watch" button. You can cancel this at any moment.

Regards,
Cecilio
