### ISSUE TITLE
How can I automatically scroll pages?

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#88]
I want to go to the next page when one page finishes when I play it automatically.

I can use the 'Interactor::new_viewport()' function to display the next page, but I do not know when the current page will end.
When the current page finishes playing, it will be good if the next page jump event occurs.
It would also be nice if there was a way to get the coordinates of the currently highlighted notes.

Please let me know if I do not know how.

**Comment by cecilios** [comment]
`Interactor::new_viewport()` function is the right method for changing the displayed page or section. But I have not thought on how to automate scrolling the music in sync. with the playback. So the API for this has to be designed and implemented. Any help, ideas and comments on how the API should be designed and on how is this implemented in other software would be of great help. As to your suggestions:

> When the current page finishes playing, it will be good if the next page jump event occurs.

My first impression is that this can be useful and it is not complex to implement. But the behaviour for the end user will not be very comfortable as the score will advance in 'jumps'. Perhaps, additional 'next system' events should be implemented, to smooth the movement.

> It would also be nice if there was a way to get the coordinates of the currently highlighted notes.

Perhaps the coordinates could be included in the highlight event, and this will save time and code and avoid having to ask for the coordinates.

In addition to all this, perhaps an additional view type could be implemented: a single system view. In this view the score will not be paginated but will flow from left to right in a single line. And for playback it will be automatically scrolled so that notes being played are always located near the left side of the screen. 

Well, I have to think in detail on all this. Currently I'm implementing all necessary support for solving #79. Hope to finish it in two-three weeks.

**Comment by juuk100** [comment]
The best way I think of scrolling is in the link below.

https://www.soundslice.com/musicxml-viewer/

But it is not too bad to jump page by page or line by line.

**Comment by cecilios** [comment]
Closed by pull-request #108
