### ISSUE TITLE
issue about example_1_win32.cpp

### ISSUE THREAD

**Issue by jellyr** [lenmus/lomse#97]
m_rbuf_window.attach(m_bitmap.buf(),
		m_bitmap.width(),
		m_bitmap.height(),
		-m_bitmap.stride()
	);

why the third argument is -m_bitmap.stride().  

when i change to  m_bitmap.stride() , it work, but the bmp is wrong , why ?

**Comment by cecilios** [comment]
Sorry, but I don't know why stride is passed as negative value in Win32 examples.

I do not use Windows. But as it is a popular choice I tried to prepare some examples for Windows. As rendering is based on agg code I just copied the Windows code from agg samples. I tested all this time ago, with Windows XP, and worked fine.

I noticed that for other platforms, agg code worked directly with native platform images. But for Windows the approach followed in agg samples was different: it defined a Bitmap class for interfacing the real Windows bitmap. But I didn't do test for using directly the Windows bitmaps, in line as it is done for the other platforms. 

If the example does not work with Windows 10, probably the Bitmap class defined in the example has to be reviewed due to some changes between WinXP and Win10.

I would suggest to study the examples for Qt and wxWidgets and try to do it in a similar way for Windows.

If you find a solution, I would appreciate if you could post it here, for the benefit of other users and for fixing the examples. Thank you.

**Comment by jellyr** [comment]
finally, i get bmp work out on windows 10.
change 

```
m_rbuf_window.attach(m_bitmap.buf(),
	m_bitmap.width(),
	m_bitmap.height(),
	-m_bitmap.stride()
```
);
to
```
	m_rbuf_window.attach(m_bitmap.buf(),
		m_bitmap.width(),
		m_bitmap.height(),
		m_bitmap.stride()
	);
```


And add 
	m_bmp->bmiHeader.biHeight =  -abs(m_bmp->bmiHeader.biHeight);
before;
	if (dvc_width != bmp_width || dvc_height != bmp_height)
	{
		::SetStretchBltMode(h_dc, COLORONCOLOR);

because msdn says 
StretchDIBits creates a top-down image if the sign of the biHeight member of the BITMAPINFOHEADER structure for the DIB is negative. For a code example, see Sizing a JPEG or PNG Image.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd145121(v=vs.85).aspx

**Comment by cecilios** [comment]
Thanks for reporting a solution.
I will keep this issue open until I have time (and a Windows machine) for fixing the example and testing it.

Thanks!!

**Comment by hugbug** [comment]
I have the same issue.

When stride is positive the image is rendered almost correctly but it's drawn mirrored from the bottom to the top of the screen:

![image](https://user-images.githubusercontent.com/3368402/38422899-a4fff8e2-39ac-11e8-9c72-8937fc745052.png)

Using negative stride would make it appear correctly, however negative stride isn't properly handled in [OverlaysGenerator](https://github.com/lenmus/lomse/blob/master/src/graphic_model/lomse_overlays_generator.cpp#L148):
```C++
//if necessary, allocate buffer for saving screen buffer
    unsigned w = m_pCanvasBuffer->width();
    unsigned h = m_pCanvasBuffer->height();
    int stride = m_pCanvasBuffer->stride();
    size_t bytes = h * stride;
```

When computing `h * stride` stride is converted to unsigned resulting in a very large calculated `bytes`, which causes memory errors later. Using of `-abs(strides)` fixes the issue:
```C++
    size_t bytes = h * abs(stride);
```
![image](https://user-images.githubusercontent.com/3368402/38422960-cdb852e8-39ac-11e8-9eb8-110bd5f49264.png)

With the fix in `OverlaysGenerator` no changes in `example_1_win32.cpp` are required.

Therefore there are two solutions:
- either allow using of negative stride for mirroring; in that case use `abs(stride)` in `OverlaysGenerator`.
- or if negative stride isn't intentional then the fix by @jellyr is more appropriate as it deals with Windows specifics in the user code part.

**Comment by cecilios** [comment]
@hugbug  Thanks for the information. My impression is that OverlaysGenerator need to be fixed, as it should also work with negative strides. And this fix is not MS Windows specific.

But the solution for Windows is not yet clear to me as the reports doesn't match.
My sample was tested (time ago) in WindowsXP and worked ok (didn't tested OverlaysGenerator that should be fixed anyway). The sample code uses negative stride.

@jellyr uses Windows10 and reports that negative stride reverses the image. To fix it, proposes:
	- to use positive stride, and
	- to use negative height, as MNSD says to do.

But you report that original code with negative stride works ok (except the bug in Overlays Generator). Which Windows version did you use for your tests?

**Comment by hugbug** [comment]
> @jellyr uses Windows10 and reports that negative stride reverses the image.

Not really. He writes:

> when i change to m_bitmap.stride() , it work, but the bmp is wrong

What he means with "wrong" is image mirroring and that happens with **positive** stride. With negative stride the program crashes (without the fix in OverlaysGenerator).

Therefore there is no contradiction in our reports.

I'm using Windows 10 but I'm 99% sure the code behave the same on Windows 10. I guess negative stride causes the image to be rendered in an opposite direction producing the same result as setting negative height.

I should a Windows XP VM. I can test there if you need.

**Comment by cecilios** [comment]
@hugbug
Thanks for your view on this.
 
> I should a Windows XP VM. I can test there if you need.

Yes, please. I no longer work with Windows and do not have Window machines. It will be great if you could test this and find a solution valid for Windows code, from WinXP to Win10.

My current point of view:
-  OverlaysGenerator must be fixed, just in case someone needs to use negative stride for some device. And this is fix platform independent.
- Negative stride in windows code looks awful to me. I'm inclined to always use positive stride, and fix the Bitmap sample code to use negative height following MSDN instructions, as pointed by jellyr.

So, what I propose to do:
- Your fix for OverlayGenerator, and
- jellyr solution for fixing sample code.

Anyway I'm open to other alternatives. Could you tests all this and prepare a PR?

**Comment by hugbug** [comment]
> Could you tests all this and prepare a PR?

I'll gladly do. This may take a couple of days though.

**Comment by cecilios** [comment]
Thank you
Take your time. There's no hurry!
